// Local destination catalog. Existing ratings are preserved. Null review counts and breakdowns mean unavailable, not zero.
const destinations = [
    {
        "name":  "Baguio",
        "province":  "Benguet",
        "island":  "Luzon",
        "category":  "Cultural",
        "cardImage":  "ILS/Luzon/Baguio/Baguio1.jpg",
        "detailImage":  "ILS/Luzon/Baguio/Baguio2.jpg",
        "quizImage":  "ILS/Luzon/Baguio/Baguio3.avif",
        "rating":  null,
        "id":  "baguio",
        "location":  "Baguio City, Benguet highlands",
        "description":  "Baguio brings together pine-covered hills, public gardens, and a lively arts scene in the Cordillera highlands. Its parks and mountain viewpoints give the city a distinctive setting.",
        "attractions":  [
                            "Burnham Park",
                            "Mines View Park",
                            "Baguio Botanical Garden",
                            "Session Road"
                        ],
        "significanceTitle":  "Cultural Significance",
        "significance":  "Baguio is a meeting place for Cordilleran traditions, contemporary art, and everyday city life. Its markets, crafts, and public spaces offer an introduction to the cultural diversity of the northern highlands.",
        "source":  "https://visita.baguio.gov.ph/",
        "reviews":  null,
        "ratingBreakdown":  null
    },
    {
        "name":  "Banaue Rice Terraces",
        "province":  "Ifugao",
        "island":  "Luzon",
        "category":  "Cultural",
        "cardImage":  "ILS/Luzon/Banaue Rice Terraces Ifugao/Banaue Rice Terraces1.jpg",
        "detailImage":  "ILS/Luzon/Banaue Rice Terraces Ifugao/Banaue Rice Terraces2.jpg",
        "quizImage":  "ILS/Luzon/Banaue Rice Terraces Ifugao/Banaue Rice Terraces3.jpg",
        "rating":  null,
        "id":  "banaue-rice-terraces",
        "location":  "Banaue, Ifugao",
        "description":  "Rice fields follow the contours of the mountains around Banaue, forming a living agricultural landscape shaped by Ifugao communities. Terraces, villages, and forested slopes are closely connected here.",
        "attractions":  [
                            "Batad Rice Terraces",
                            "Bangaan Rice Terraces",
                            "Banaue terrace viewpoints",
                            "Ifugao weaving and farming traditions"
                        ],
        "significanceTitle":  "Cultural Significance",
        "significance":  "The terraces reflect generations of Ifugao knowledge of irrigation, farming, and care for the surrounding forests. Batad and Bangaan, both in Banaue municipality, are among the terrace clusters inscribed on UNESCO\u0027s World Heritage List.",
        "source":  "https://whc.unesco.org/en/tentativelists/6721",
        "reviews":  null,
        "ratingBreakdown":  null
    },
    {
        "name":  "Hundred Islands National Park",
        "province":  "Pangasinan",
        "island":  "Luzon",
        "category":  "Island",
        "cardImage":  "ILS/Luzon/hundred Islands Pangasinan/Hundred Islands National Park1.jpg",
        "detailImage":  "ILS/Luzon/hundred Islands Pangasinan/Hundred Islands National Park2.webp",
        "quizImage":  "ILS/Luzon/hundred Islands Pangasinan/Hundred Islands National Park3.jpg",
        "rating":  null,
        "id":  "hundred-islands-national-park",
        "location":  "Alaminos, Pangasinan",
        "description":  "Small limestone islands rise from the waters of Lingayen Gulf at Hundred Islands National Park. Beaches, coves, and elevated viewpoints reveal different perspectives on the island group.",
        "attractions":  [
                            "Governor\u0027s Island",
                            "Quezon Island",
                            "Children\u0027s Island",
                            "Island-hopping scenery"
                        ],
        "significanceTitle":  "Natural Significance",
        "significance":  "The islands form a distinctive coastal landscape shaped by limestone and the sea. Their shores and surrounding waters connect Pangasinan\u0027s marine environment with local coastal tourism.",
        "reviews":  null,
        "ratingBreakdown":  null,
        "source":  "https://www.tourism.gov.ph/destination/ilocos-region/pangasinan/"
    },
    {
        "name":  "Intramuros",
        "province":  "Manila",
        "island":  "Luzon",
        "category":  "Historical",
        "cardImage":  "ILS/Luzon/Intramuros MNL/Fort Santiago.jpg",
        "detailImage":  "ILS/Luzon/Intramuros MNL/Fort Santiago2.jpg",
        "quizImage":  "ILS/Luzon/Intramuros MNL/Fort Santiago3.jpg",
        "rating":  null,
        "id":  "intramuros",
        "location":  "Intramuros, Manila",
        "description":  "Intramuros is Manila\u0027s historic walled district, where stone fortifications, churches, and streets preserve traces of the city\u0027s past. Fort Santiago is one of its best-known landmarks.",
        "attractions":  [
                            "Fort Santiago",
                            "San Agustin Church",
                            "Manila Cathedral",
                            "Historic city walls"
                        ],
        "significanceTitle":  "Historical Significance",
        "significance":  "Intramuros was a center of political and religious life during the Spanish colonial period. Its surviving and restored landmarks provide places to learn about colonial Manila, Jose Rizal, and the city\u0027s wartime history.",
        "imageCaption":  "Fort Santiago · Intramuros, Manila",
        "imageAlt":  "Fort Santiago in the historic district of Intramuros",
        "reviews":  null,
        "ratingBreakdown":  null,
        "source":  "https://intramuros.gov.ph/sites/"
    },
    {
        "name":  "Mayon Volcano",
        "province":  "Albay",
        "island":  "Luzon",
        "category":  "Mountain",
        "cardImage":  "ILS/Luzon/Mayon Volcano Albay/Cagsawa Ruins1.jpg",
        "detailImage":  "ILS/Luzon/Mayon Volcano Albay/Cagsawa Ruins2.jpg",
        "quizImage":  "ILS/Luzon/Mayon Volcano Albay/Cagsawa Ruins3.jpg",
        "rating":  4.8,
        "id":  "mayon-volcano",
        "location":  "Albay, Bicol Region",
        "description":  "Mayon\u0027s striking volcanic cone dominates the Albay landscape. Views from the surrounding towns pair its mountain silhouette with farmland, historic buildings, and open countryside.",
        "attractions":  [
                            "Cagsawa Ruins",
                            "Daraga Church",
                            "Albay countryside viewpoints",
                            "Mayon\u0027s volcanic landscape"
                        ],
        "significanceTitle":  "Natural Significance",
        "significance":  "Mayon is an active volcano and a defining symbol of Albay. Its presence has shaped the region\u0027s landscapes, settlements, and stories, making it central to Bicol\u0027s natural and cultural identity.",
        "imageCaption":  "Cagsawa Ruins · Albay",
        "imageAlt":  "Cagsawa Ruins in the landscape surrounding Mayon Volcano",
        "reviews":  null,
        "ratingBreakdown":  null,
        "source":  "https://www.tourism.gov.ph/article/a-bicol-and-central-visayas-travel-bucket-list-for-cyclists-3/"
    },
    {
        "name":  "Mount Pinatubo",
        "province":  "Zambales, Tarlac and Pampanga",
        "island":  "Luzon",
        "category":  "Mountain",
        "cardImage":  "ILS/Luzon/Mt. Pinatubo/Mt. Pinatubo Crater Lake.webp",
        "detailImage":  "ILS/Luzon/Mt. Pinatubo/Mt. Pinatubo Crater Lake2.webp",
        "quizImage":  "ILS/Luzon/Mt. Pinatubo/Mt. Pinatubo Crater Lake3.webp",
        "rating":  null,
        "id":  "mount-pinatubo",
        "location":  "Zambales, Tarlac and Pampanga",
        "description":  "Mount Pinatubo is known for its crater lake and dramatic volcanic terrain. Pale deposits, rugged valleys, and steep crater walls reveal a landscape transformed by eruption.",
        "attractions":  [
                            "Pinatubo crater lake",
                            "Crater-wall scenery",
                            "Lahar-shaped valleys",
                            "Volcanic rock formations"
                        ],
        "significanceTitle":  "Natural Significance",
        "significance":  "Pinatubo\u0027s 1991 eruption reshaped large parts of Central Luzon and affected communities far beyond the mountain. Its crater and surrounding deposits are visible reminders of the power of volcanic processes.",
        "reviews":  null,
        "ratingBreakdown":  null,
        "source":  "https://pubs.usgs.gov/fs/1997/fs113-97/"
    },
    {
        "name":  "Puerto Princesa Underground River",
        "province":  "Palawan",
        "island":  "Luzon",
        "category":  "Natural Landmark",
        "cardImage":  "ILS/Luzon/Puerto Prinsesa Underground River Palawan/Puerto Princesa Underground River1.jpg",
        "detailImage":  "ILS/Luzon/Puerto Prinsesa Underground River Palawan/Puerto Princesa Underground River2.jpg",
        "quizImage":  "ILS/Luzon/Puerto Prinsesa Underground River Palawan/Puerto Princesa Underground River3.jpg",
        "rating":  null,
        "id":  "puerto-princesa-underground-river",
        "location":  "Sabang, Puerto Princesa, Palawan",
        "description":  "A river passes through a limestone cave system before reaching the sea near Sabang. Forest, dramatic karst formations, and coastal scenery surround this Palawan landmark.",
        "attractions":  [
                            "Underground river cave",
                            "Limestone chambers and formations",
                            "Sabang coastline",
                            "Surrounding forest landscape"
                        ],
        "significanceTitle":  "Ecological Significance",
        "significance":  "The park brings together forest, limestone, and marine environments in a connected landscape. Its underground river and biodiversity are central to its recognition as a UNESCO World Heritage Site.",
        "reviews":  null,
        "ratingBreakdown":  null,
        "source":  "https://whc.unesco.org/en/list/652"
    },
    {
        "name":  "Taal Volcano",
        "province":  "Batangas",
        "island":  "Luzon",
        "category":  "Mountain",
        "cardImage":  "ILS/Luzon/Taal Volcano Batangas/Taal Lake1.webp",
        "detailImage":  "ILS/Luzon/Taal Volcano Batangas/Taal Lake2.webp",
        "quizImage":  "ILS/Luzon/Taal Volcano Batangas/Taal Lake3.webp",
        "rating":  null,
        "id":  "taal-volcano",
        "location":  "Taal Lake, Batangas",
        "description":  "Taal Volcano rises within Taal Lake, creating one of southern Luzon\u0027s most recognizable volcanic landscapes. Distant viewpoints show the relationship between the lake, Volcano Island, and surrounding ridges.",
        "attractions":  [
                            "Taal Lake panorama",
                            "Volcano Island views from the mainland",
                            "Tagaytay ridge viewpoints",
                            "Batangas lakeside scenery"
                        ],
        "significanceTitle":  "Natural Significance",
        "significance":  "Taal is an active volcanic system whose eruptions have shaped the lake basin and neighboring communities. The landscape illustrates how geological forces and life around a lake remain closely connected.",
        "imageCaption":  "Taal Lake and its volcanic landscape · Batangas",
        "reviews":  null,
        "ratingBreakdown":  null,
        "source":  "https://www.phivolcs.dost.gov.ph/taal-volcano-article-perla-j-delos-reyes-ma-antonia-v-bornas-dale-dominey-howes-abigail-c-pidlaoan-christina-r-magill-and-renato-u-solidum-jr-a-synthesis-and-review-of-historical-eruptions-at-taal-vol/"
    },
    {
        "name":  "Tagaytay",
        "province":  "Cavite",
        "island":  "Luzon",
        "category":  "Natural Landmark",
        "cardImage":  "ILS/Luzon/Tagaytay/Tagaytay1.jpg",
        "detailImage":  "ILS/Luzon/Tagaytay/Tagaytay2.jpg",
        "quizImage":  "ILS/Luzon/Tagaytay/Tagaytay3.jpg",
        "rating":  4.7,
        "id":  "tagaytay",
        "location":  "Tagaytay City, Cavite",
        "description":  "Tagaytay sits on a ridge overlooking Taal Lake and the volcanic landscape of Batangas. Gardens, parks, and scenic viewpoints are part of the city\u0027s familiar highland atmosphere.",
        "attractions":  [
                            "Taal Lake viewpoints",
                            "Picnic Grove",
                            "People\u0027s Park in the Sky",
                            "Sky Ranch"
                        ],
        "significanceTitle":  "Tourism Significance",
        "significance":  "Tagaytay offers a broad view of the Taal landscape from the surrounding ridge. Its parks, food culture, and proximity to Metro Manila have made it a well-known destination for short countryside breaks.",
        "reviews":  null,
        "ratingBreakdown":  null,
        "source":  "https://www.tourism.gov.ph/destination/calabarzon/city-of-tagaytay/"
    },
    {
        "name":  "Vigan",
        "province":  "Ilocos Sur",
        "island":  "Luzon",
        "category":  "Historical",
        "cardImage":  "ILS/Luzon/Vigan/Calle Crisologo1.png",
        "detailImage":  "ILS/Luzon/Vigan/Calle Crisologo2.webp",
        "quizImage":  "ILS/Luzon/Vigan/Calle Crisologo3.jpg",
        "rating":  null,
        "id":  "vigan",
        "location":  "Vigan City, Ilocos Sur",
        "description":  "Vigan is known for its historic streets, ancestral houses, and distinctive urban character. Calle Crisologo is a prominent part of its preserved heritage district.",
        "attractions":  [
                            "Calle Crisologo",
                            "Vigan Cathedral",
                            "Plaza Salcedo",
                            "Traditional burnay pottery"
                        ],
        "significanceTitle":  "Historical Significance",
        "significance":  "Vigan\u0027s architecture and street plan reflect Filipino, Chinese, and European influences. Its historic center preserves an important record of trade and urban life during the colonial period.",
        "source":  "https://philippines.travel/destinations/vigan/index",
        "imageCaption":  "Calle Crisologo · Vigan",
        "reviews":  null,
        "ratingBreakdown":  null
    },
    {
        "name":  "Apo Island",
        "province":  "Negros Oriental",
        "island":  "Visayas",
        "category":  "Island",
        "cardImage":  "ILS/Visayas/Apo Island Negros Oriental/Apo-island-reef.webp",
        "detailImage":  "ILS/Visayas/Apo Island Negros Oriental/Apo-island-reef.webp",
        "quizImage":  "ILS/Visayas/Apo Island Negros Oriental/Apo-island-reef.webp",
        "rating":  null,
        "id":  "apo-island",
        "location":  "Dauin, Negros Oriental",
        "description":  "Apo Island is a small island community surrounded by coral reefs off Negros Oriental. Its clear coastal waters and marine life make the underwater landscape a central part of its identity.",
        "attractions":  [
                            "Coral reef habitats",
                            "Sea turtle encounters",
                            "Marine sanctuary",
                            "Island village and coastal views"
                        ],
        "significanceTitle":  "Ecological Significance",
        "significance":  "Apo Island is widely recognized for community-based marine conservation. The relationship between residents, reef protection, and local livelihoods makes it an important example of caring for coastal ecosystems.",
        "source":  "https://www.tourism.gov.ph/destination/nir/negros-oriental/",
        "reviews":  null,
        "ratingBreakdown":  null
    },
    {
        "name":  "Boracay",
        "province":  "Aklan",
        "island":  "Visayas",
        "category":  "Beach",
        "cardImage":  "ILS/Visayas/Boracay/Boracay1.webp",
        "detailImage":  "ILS/Visayas/Boracay/Boracay2.webp",
        "quizImage":  "ILS/Visayas/Boracay/Boracay3.webp",
        "rating":  4.9,
        "id":  "boracay",
        "location":  "Malay, Aklan",
        "description":  "Boracay is known for pale sand, clear coastal waters, and its lively beachfront. White Beach and the island\u0027s quieter shores offer different sides of this well-known Visayan destination.",
        "attractions":  [
                            "White Beach",
                            "Puka Shell Beach",
                            "Bulabog Beach",
                            "Sunset views along the western shore"
                        ],
        "significanceTitle":  "Natural / Tourism Significance",
        "significance":  "Boracay\u0027s beaches have made it one of the Philippines\u0027 best-known island destinations. Its appeal also highlights the importance of protecting coastal water quality and balancing tourism with the island\u0027s environment.",
        "source":  "https://www.philippines.travel/activities/beaches",
        "reviews":  null,
        "ratingBreakdown":  null
    },
    {
        "name":  "Cebu",
        "province":  "Cebu",
        "island":  "Visayas",
        "category":  "Natural Landmark",
        "cardImage":  "ILS/Visayas/Cebu/Kawasan Falls.webp",
        "detailImage":  "ILS/Visayas/Cebu/Kawasan Falls2.webp",
        "quizImage":  "ILS/Visayas/Cebu/Kawasan Falls3.webp",
        "rating":  null,
        "id":  "cebu",
        "location":  "Cebu Province, Central Visayas",
        "description":  "Cebu combines historic city landmarks with beaches, mountain scenery, and waterfalls. The existing photograph shows Kawasan Falls, one of the province\u0027s natural attractions.",
        "attractions":  [
                            "Kawasan Falls",
                            "Magellan\u0027s Cross",
                            "Basilica Minore del Santo Niño",
                            "Moalboal marine life"
                        ],
        "significanceTitle":  "Historical / Natural Significance",
        "significance":  "Cebu holds an important place in the history of Spanish contact and Christianity in the Philippines. Beyond the city, its coastlines and inland landscapes show the natural diversity of the Visayas.",
        "imageCaption":  "Kawasan Falls · Cebu Province",
        "imageAlt":  "Kawasan Falls, one of Cebu Province\u0027s natural attractions",
        "reviews":  null,
        "ratingBreakdown":  null,
        "source":  "https://www.tourism.gov.ph/destination/central-visayas/cebu-province/"
    },
    {
        "name":  "Chocolate Hills",
        "province":  "Bohol",
        "island":  "Visayas",
        "category":  "Natural Landmark",
        "cardImage":  "ILS/Visayas/Chocolate Hills Bohol/Chocolate Hills1.webp",
        "detailImage":  "ILS/Visayas/Chocolate Hills Bohol/Chocolate Hills2.jpg",
        "quizImage":  "ILS/Visayas/Chocolate Hills Bohol/Chocolate Hills3.jpg",
        "rating":  4.8,
        "id":  "chocolate-hills",
        "location":  "Carmen and surrounding towns, Bohol",
        "description":  "Rounded hills spread across the interior of Bohol in a distinctive rolling landscape. Their grass can turn brown during dry periods, giving the Chocolate Hills their familiar name.",
        "attractions":  [
                            "Chocolate Hills viewing deck in Carmen",
                            "Panoramic hill scenery",
                            "Seasonal green and brown grasslands",
                            "Bohol countryside landscapes"
                        ],
        "significanceTitle":  "Natural Significance",
        "significance":  "The Chocolate Hills are a notable limestone landscape and a symbol of Bohol. Their repeated rounded shapes make the area\u0027s geological character visible on an unusually broad scale.",
        "reviews":  null,
        "ratingBreakdown":  null,
        "source":  "https://tourism.bohol.gov.ph/2023/04/04/exploring-bohol-island-a-gem-in-visayas-philippines/"
    },
    {
        "name":  "Dumaguete",
        "province":  "Negros Oriental",
        "island":  "Visayas",
        "category":  "Cultural",
        "cardImage":  "ILS/Visayas/Dumaguete Negros Oriental/Rizal Boulevard1.jpg",
        "detailImage":  "ILS/Visayas/Dumaguete Negros Oriental/Rizal Boulevard2.webp",
        "quizImage":  "ILS/Visayas/Dumaguete Negros Oriental/Rizal Boulevard3.jpg",
        "rating":  null,
        "id":  "dumaguete",
        "location":  "Dumaguete City, Negros Oriental",
        "description":  "Dumaguete is a coastal university city with a walkable waterfront and historic landmarks. Rizal Boulevard links the city center with views over the sea.",
        "attractions":  [
                            "Rizal Boulevard",
                            "Silliman University campus",
                            "Dumaguete Belfry",
                            "St. Catherine of Alexandria Cathedral"
                        ],
        "significanceTitle":  "Cultural Significance",
        "significance":  "Dumaguete\u0027s universities and creative communities have helped shape its identity as a center for learning and the arts. Its waterfront and historic core connect this cultural life with the city\u0027s coastal setting.",
        "imageCaption":  "Rizal Boulevard · Dumaguete",
        "reviews":  null,
        "ratingBreakdown":  null,
        "source":  "https://dumaguetecity.gov.ph/2018/11/19/paseo-de-rizal-or-the-rizal-boulevard/"
    },
    {
        "name":  "Gigantes Islands",
        "province":  "Iloilo",
        "island":  "Visayas",
        "category":  "Island",
        "cardImage":  "ILS/Visayas/Gigantes Island Iloilo/f70f61e4-f799-47ec-980d-77b8cb32d9d5.jpg",
        "detailImage":  "ILS/Visayas/Gigantes Island Iloilo/f70f61e4-f799-47ec-980d-77b8cb32d9d5.jpg",
        "quizImage":  "ILS/Visayas/Gigantes Island Iloilo/f70f61e4-f799-47ec-980d-77b8cb32d9d5.jpg",
        "rating":  null,
        "id":  "gigantes-islands",
        "location":  "Carles, Iloilo",
        "description":  "The Gigantes Islands bring together limestone formations, small beaches, and fishing communities off northern Iloilo. Sandbars and sheltered waters add variety to the island scenery.",
        "attractions":  [
                            "Cabugao Gamay Island",
                            "Tangke lagoon",
                            "Bantigue sandbar",
                            "Antonia Beach"
                        ],
        "significanceTitle":  "Natural Significance",
        "significance":  "The islands show how limestone formations and coastal waters create a varied marine landscape. Fishing and island tourism connect local livelihoods with the health of these shores and surrounding waters.",
        "source":  "https://denr.gov.ph/wp-content/uploads/2023/07/News_Monitoring_09_03_2019a.pdf",
        "reviews":  null,
        "ratingBreakdown":  null
    },
    {
        "name":  "Kalanggaman Island",
        "province":  "Leyte",
        "island":  "Visayas",
        "category":  "Island",
        "cardImage":  "ILS/Visayas/Kalanggaman Island Leyte/Kalanggaman-Island-1-1-1024x576.jpg",
        "detailImage":  "ILS/Visayas/Kalanggaman Island Leyte/Kalanggaman-Island-1-1-1024x576.jpg",
        "quizImage":  "ILS/Visayas/Kalanggaman Island Leyte/Kalanggaman-Island-1-1-1024x576.jpg",
        "rating":  null,
        "id":  "kalanggaman-island",
        "location":  "Palompon, Leyte",
        "description":  "Kalanggaman is a small island known for its long sandbar and clear surrounding water. Palm trees and open sea views give its narrow shoreline a distinctive appearance.",
        "attractions":  [
                            "Kalanggaman sandbar",
                            "White-sand shoreline",
                            "Palm-lined island scenery",
                            "Clear-water coastal views"
                        ],
        "significanceTitle":  "Natural Significance",
        "significance":  "Kalanggaman\u0027s changing sandbar illustrates the movement of sand along a small island coast. Its compact landscape makes care for shoreline habitats and surrounding waters especially important.",
        "source":  "https://www.tourism.gov.ph/destination/eastern-visayas/leyte/",
        "reviews":  null,
        "ratingBreakdown":  null
    },
    {
        "name":  "Kawasan Falls",
        "province":  "Cebu",
        "island":  "Visayas",
        "category":  "Waterfall",
        "cardImage":  "ILS/Visayas/Kawasan Falls Cebu/Drone+photo+of+Kawasan+Falls,+Cebu,+The+Philippines.jpeg",
        "detailImage":  "ILS/Visayas/Kawasan Falls Cebu/Drone+photo+of+Kawasan+Falls,+Cebu,+The+Philippines.jpeg",
        "quizImage":  "ILS/Visayas/Kawasan Falls Cebu/Drone+photo+of+Kawasan+Falls,+Cebu,+The+Philippines.jpeg",
        "rating":  null,
        "id":  "kawasan-falls",
        "location":  "Badian, Cebu",
        "description":  "Kawasan Falls is a series of cascades and blue-green pools in southern Cebu. Dense vegetation and limestone scenery frame the flowing water.",
        "attractions":  [
                            "Main Kawasan cascade",
                            "Blue-green pools",
                            "River and limestone scenery",
                            "Forested waterfall surroundings"
                        ],
        "significanceTitle":  "Natural Significance",
        "significance":  "Kawasan is one of Cebu\u0027s recognizable freshwater landscapes. The falls show the close connection between upstream waterways, forested surroundings, and the quality of the pools below.",
        "reviews":  null,
        "ratingBreakdown":  null,
        "source":  "https://www.tourism.gov.ph/destination/central-visayas/cebu-province/"
    },
    {
        "name":  "Sambawan Island",
        "province":  "Biliran",
        "island":  "Visayas",
        "category":  "Island",
        "cardImage":  "ILS/Visayas/Sambawan Island Biliran/photo0jpg.jpg",
        "detailImage":  "ILS/Visayas/Sambawan Island Biliran/photo0jpg.jpg",
        "quizImage":  "ILS/Visayas/Sambawan Island Biliran/photo0jpg.jpg",
        "rating":  null,
        "id":  "sambawan-island",
        "location":  "Maripipi, Biliran",
        "description":  "Sambawan\u0027s grassy hills rise above pale beaches and blue water near Maripipi. Its elevated viewpoints reveal the curves of the shoreline and the neighboring island landscape.",
        "attractions":  [
                            "Hilltop viewpoint",
                            "Curving beach shoreline",
                            "Views toward Maripipi",
                            "Coastal and reef scenery"
                        ],
        "significanceTitle":  "Natural Significance",
        "significance":  "Sambawan combines small-island coastlines with distinctive rolling hills. Its scenery is closely linked to the surrounding sea, making the island a recognizable part of Biliran\u0027s natural heritage.",
        "source":  "https://biliran.gov.ph/2024/10/08/sambawan-island/",
        "reviews":  null,
        "ratingBreakdown":  null
    },
    {
        "name":  "Siquijor",
        "province":  "Siquijor",
        "island":  "Visayas",
        "category":  "Island",
        "cardImage":  "ILS/Visayas/Siquijor/Siquijor1.webp",
        "detailImage":  "ILS/Visayas/Siquijor/Siquijor2.jpg",
        "quizImage":  "ILS/Visayas/Siquijor/Siquijor3.jpg",
        "rating":  null,
        "id":  "siquijor",
        "location":  "Siquijor Province, Visayas",
        "description":  "Siquijor combines beaches, waterfalls, and heritage buildings with a strong local cultural identity. Coastal roads connect towns, inland greenery, and views of the surrounding sea.",
        "attractions":  [
                            "Cambugahay Falls",
                            "Paliton Beach",
                            "Lazi Church and Convent",
                            "Old balete tree in Lazi"
                        ],
        "significanceTitle":  "Cultural / Natural Significance",
        "significance":  "Siquijor\u0027s identity includes local healing traditions, historic religious buildings, and a close relationship with its island environment. Its cultural stories and natural landscapes offer complementary ways to understand the province.",
        "source":  "https://philippines.travel/destinations/siquijor/index",
        "reviews":  null,
        "ratingBreakdown":  null
    },
    {
        "name":  "Aliwagwag Falls",
        "province":  "Davao Oriental",
        "island":  "Mindanao",
        "category":  "Waterfall",
        "cardImage":  "ILS/Mindanao/Aliwagwag Falls Davao Oriental/MWS-Aliwagwag-Falls.jpg",
        "detailImage":  "ILS/Mindanao/Aliwagwag Falls Davao Oriental/MWS-Aliwagwag-Falls.jpg",
        "quizImage":  "ILS/Mindanao/Aliwagwag Falls Davao Oriental/MWS-Aliwagwag-Falls.jpg",
        "rating":  null,
        "id":  "aliwagwag-falls",
        "location":  "Cateel, Davao Oriental",
        "description":  "Aliwagwag is a broad series of cascades flowing over stepped rock formations. Forested surroundings frame the river as it descends through the landscape of Cateel.",
        "attractions":  [
                            "Tiered waterfall cascades",
                            "Stepped rock formations",
                            "Aliwagwag River scenery",
                            "Forested watershed landscape"
                        ],
        "significanceTitle":  "Ecological Significance",
        "significance":  "Aliwagwag\u0027s cascades form part of a river and forest landscape in eastern Mindanao. Caring for the watershed helps preserve both the falls and the water resources connected to the river.",
        "source":  "https://r11.emb.gov.ph/stakeholders-convene-to-suport-class-a-classification-of-aliwagwag-river/",
        "reviews":  null,
        "ratingBreakdown":  null
    },
    {
        "name":  "Asik-asik Falls",
        "province":  "Cotabato",
        "island":  "Mindanao",
        "category":  "Waterfall",
        "cardImage":  "ILS/Mindanao/Asik-asik Falls Cotabato/Asik-Asik_Falls,_Alamada,_Cotabato.jpg",
        "detailImage":  "ILS/Mindanao/Asik-asik Falls Cotabato/Asik-Asik_Falls,_Alamada,_Cotabato.jpg",
        "quizImage":  "ILS/Mindanao/Asik-asik Falls Cotabato/Asik-Asik_Falls,_Alamada,_Cotabato.jpg",
        "rating":  null,
        "id":  "asik-asik-falls",
        "location":  "Dado, Alamada, Cotabato",
        "description":  "At Asik-asik, water emerges across a plant-covered cliff in fine streams and curtains. The greenery and spreading flow distinguish it from a waterfall with a single large drop.",
        "attractions":  [
                            "Curtain-like waterfall streams",
                            "Plant-covered cliff face",
                            "Moss and fern scenery",
                            "Alamada highland landscape"
                        ],
        "significanceTitle":  "Natural Significance",
        "significance":  "Asik-asik\u0027s appeal lies in the unusual pattern of water emerging through a green cliff face. It is a distinctive example of the relationship between water, rock, and vegetation in Cotabato\u0027s uplands.",
        "source":  "https://www.alamada.gov.ph/tourism-culture-arts-office/local-attractions/",
        "reviews":  null,
        "ratingBreakdown":  null
    },
    {
        "name":  "Camiguin",
        "province":  "Camiguin",
        "island":  "Mindanao",
        "category":  "Island",
        "cardImage":  "ILS/Mindanao/Camiguin/Camiguin-Travel-Guide-_-White-Island--scaled.jpeg",
        "detailImage":  "ILS/Mindanao/Camiguin/Camiguin-Travel-Guide-_-White-Island--scaled.jpeg",
        "quizImage":  "ILS/Mindanao/Camiguin/Camiguin-Travel-Guide-_-White-Island--scaled.jpeg",
        "rating":  null,
        "id":  "camiguin",
        "location":  "Camiguin Province, Northern Mindanao",
        "description":  "Camiguin is a volcanic island with mountain slopes, waterfalls, springs, and small offshore islands. Its landscape brings together traces of volcanic history and tropical coastal scenery.",
        "attractions":  [
                            "White Island",
                            "Sunken Cemetery",
                            "Katibawasan Falls",
                            "Mantigue Island"
                        ],
        "significanceTitle":  "Natural / Historical Significance",
        "significance":  "Volcanic activity has shaped both Camiguin\u0027s terrain and the history of its communities. Landmarks such as the Sunken Cemetery connect that geological story with the lives and memories of island residents.",
        "source":  "https://philippines.travel/destinations/camiguin/index",
        "reviews":  null,
        "ratingBreakdown":  null
    },
    {
        "name":  "Dahican Beach",
        "province":  "Davao Oriental",
        "island":  "Mindanao",
        "category":  "Beach",
        "cardImage":  "ILS/Mindanao/Dahican Beach Davao Oriental/DSC_8857 (1).jpg",
        "detailImage":  "ILS/Mindanao/Dahican Beach Davao Oriental/DSC_8857 (1).jpg",
        "quizImage":  "ILS/Mindanao/Dahican Beach Davao Oriental/DSC_8857 (1).jpg",
        "rating":  null,
        "id":  "dahican-beach",
        "location":  "Mati City, Davao Oriental",
        "description":  "Dahican is a long sandy beach facing the Pacific in Mati. Its open coastline is associated with waves, skimboarding, and sea turtle nesting habitat.",
        "attractions":  [
                            "Dahican\u0027s sandy shoreline",
                            "Skimboarding culture",
                            "Pacific surf scenery",
                            "Sea turtle conservation"
                        ],
        "significanceTitle":  "Ecological / Tourism Significance",
        "significance":  "Dahican connects a local board-sport culture with a coast used by nesting sea turtles. The beach\u0027s value extends beyond recreation to the marine life that depends on its shoreline.",
        "source":  "https://phworldexpo.tpb.gov.ph/dahican-beach/",
        "reviews":  null,
        "ratingBreakdown":  null
    },
    {
        "name":  "Enchanted River",
        "province":  "Surigao del Sur",
        "island":  "Mindanao",
        "category":  "Natural Landmark",
        "cardImage":  "ILS/Mindanao/Enchanted River Surigao del sur/Hinatuan-C0UdX.jpg",
        "detailImage":  "ILS/Mindanao/Enchanted River Surigao del sur/Hinatuan-C0UdX.jpg",
        "quizImage":  "ILS/Mindanao/Enchanted River Surigao del sur/Hinatuan-C0UdX.jpg",
        "rating":  null,
        "id":  "enchanted-river",
        "location":  "Hinatuan, Surigao del Sur",
        "description":  "Hinatuan\u0027s Enchanted River is known for its striking blue water and a deep pool surrounded by vegetation. The short river is one of Surigao del Sur\u0027s distinctive natural landmarks.",
        "attractions":  [
                            "Blue spring-pool views",
                            "Riverbank scenery",
                            "Fish in the clear water",
                            "Hinatuan\u0027s coastal surroundings"
                        ],
        "significanceTitle":  "Ecological Significance",
        "significance":  "The river\u0027s clear water is central to its natural appeal and local tourism identity. Conservation efforts around the river show the importance of protecting water quality and managing the surrounding environment.",
        "source":  "https://caraga.emb.gov.ph/restoring-herucs-lgu-hinatuans-responses-to-the-challenges-of-enchanted-rive/",
        "reviews":  null,
        "ratingBreakdown":  null
    },
    {
        "name":  "Lake Sebu",
        "province":  "South Cotabato",
        "island":  "Mindanao",
        "category":  "Natural Landmark",
        "cardImage":  "ILS/Mindanao/Lake Sebu South Cotabato/nature-s-beauty-of-7.jpg",
        "detailImage":  "ILS/Mindanao/Lake Sebu South Cotabato/nature-s-beauty-of-7.jpg",
        "quizImage":  "ILS/Mindanao/Lake Sebu South Cotabato/nature-s-beauty-of-7.jpg",
        "rating":  null,
        "id":  "lake-sebu",
        "location":  "Lake Sebu, South Cotabato",
        "description":  "Lake Sebu brings together lake scenery, waterfalls, and T\u0027boli cultural traditions in South Cotabato. Water, forests, and community life are closely woven into its identity.",
        "attractions":  [
                            "Lake Sebu shoreline",
                            "Seven Falls",
                            "T\u0027nalak weaving",
                            "T\u0027boli music and crafts"
                        ],
        "significanceTitle":  "Cultural Significance",
        "significance":  "Lake Sebu is closely associated with T\u0027boli heritage, including the weaving of t\u0027nalak cloth. Its communities preserve knowledge and artistic traditions that give the lake district significance beyond its scenery.",
        "source":  "https://southcotabato.gov.ph/lake-sebu-is-top-tourist-destination-in-soutn-cotabato/",
        "reviews":  null,
        "ratingBreakdown":  null
    },
    {
        "name":  "Mount Apo",
        "province":  "Davao del Sur and Cotabato",
        "island":  "Mindanao",
        "category":  "Mountain",
        "cardImage":  "ILS/Mindanao/Mt. Apo Davao/mount-apo.jpg",
        "detailImage":  "ILS/Mindanao/Mt. Apo Davao/mount-apo.jpg",
        "quizImage":  "ILS/Mindanao/Mt. Apo Davao/mount-apo.jpg",
        "rating":  null,
        "id":  "mount-apo",
        "location":  "Davao del Sur and Cotabato",
        "description":  "Mount Apo is the Philippines\u0027 highest mountain, rising above a varied landscape of forests and rocky uplands. Its broad mountain environment is one of Mindanao\u0027s defining natural features.",
        "attractions":  [
                            "High-elevation mountain scenery",
                            "Montane forest habitats",
                            "Rocky summit landscape",
                            "Lake Venado"
                        ],
        "significanceTitle":  "Ecological / Cultural Significance",
        "significance":  "Mount Apo supports important upland habitats and holds cultural significance for Indigenous communities around the mountain. Its forests and watersheds connect the highlands with the landscapes below.",
        "source":  "https://www.tourism.gov.ph/destination/davao-region/davao-del-sur/",
        "reviews":  null,
        "ratingBreakdown":  null
    },
    {
        "name":  "Siargao",
        "province":  "Surigao del Norte",
        "island":  "Mindanao",
        "category":  "Island",
        "cardImage":  "ILS/Mindanao/Siargao/guyam-island-siargao-travel-guide-1-1.png",
        "detailImage":  "ILS/Mindanao/Siargao/guyam-island-siargao-travel-guide-1-1.png",
        "quizImage":  "ILS/Mindanao/Siargao/guyam-island-siargao-travel-guide-1-1.png",
        "rating":  4.9,
        "id":  "siargao",
        "location":  "Siargao Island, Surigao del Norte",
        "description":  "Siargao combines a well-known surfing culture with palm-lined coasts, lagoons, and offshore islands. Its scenery extends from the waves around General Luna to quieter coastal communities.",
        "attractions":  [
                            "Cloud 9 surf area",
                            "Guyam Island",
                            "Daku Island",
                            "Sugba Lagoon"
                        ],
        "significanceTitle":  "Natural / Tourism Significance",
        "significance":  "Siargao\u0027s waves have helped shape its identity as a surfing destination. Its coastal habitats and island communities are equally important parts of a landscape that supports both everyday livelihoods and tourism.",
        "imageCaption":  "Guyam Island · Siargao\u0027s neighboring islands",
        "imageAlt":  "Guyam Island near Siargao",
        "reviews":  null,
        "ratingBreakdown":  null,
        "source":  "https://www.tourism.gov.ph/destination/caraga/siargao-island/"
    },
    {
        "name":  "Santa Cruz Island",
        "province":  "Zamboanga City",
        "island":  "Mindanao",
        "category":  "Island",
        "cardImage":  "ILS/Mindanao/Sta. Cruz island Zamboanga/IMG_1014-1024x576.jpg",
        "detailImage":  "ILS/Mindanao/Sta. Cruz island Zamboanga/IMG_1014-1024x576.jpg",
        "quizImage":  "ILS/Mindanao/Sta. Cruz island Zamboanga/IMG_1014-1024x576.jpg",
        "rating":  null,
        "id":  "santa-cruz-island",
        "location":  "Great Santa Cruz Island, Zamboanga City",
        "description":  "Great Santa Cruz Island is known for sand with a subtle pink hue, set against clear coastal waters. A mangrove lagoon adds another distinctive habitat to the island.",
        "attractions":  [
                            "Pink-sand shoreline",
                            "Mangrove lagoon",
                            "Coastal waters",
                            "Views across to Zamboanga"
                        ],
        "significanceTitle":  "Ecological Significance",
        "significance":  "Fragments of red organ-pipe coral mixed with pale sand give the beach its characteristic tint. The mangroves and coastal habitats show how the island\u0027s appeal depends on the health of its marine environment.",
        "source":  "https://www.tourism.gov.ph/article/10-instagrammable-spots-in-zamboanga-peninsula/",
        "reviews":  null,
        "ratingBreakdown":  null
    },
    {
        "name":  "Tinago Falls",
        "province":  "Lanao del Norte",
        "island":  "Mindanao",
        "category":  "Waterfall",
        "cardImage":  "ILS/Mindanao/Tinago Falls Lanao Del Norte/tinago-falls.jpg",
        "detailImage":  "ILS/Mindanao/Tinago Falls Lanao Del Norte/tinago-falls.jpg",
        "quizImage":  "ILS/Mindanao/Tinago Falls Lanao Del Norte/tinago-falls.jpg",
        "rating":  null,
        "id":  "tinago-falls",
        "location":  "Linamon, Lanao del Norte, near Iligan City",
        "description":  "Tinago Falls drops into a deep blue-green pool framed by rock and dense vegetation. Its enclosed setting gives the cascade a secluded appearance.",
        "attractions":  [
                            "Main waterfall cascade",
                            "Blue-green plunge pool",
                            "Rocky ravine scenery",
                            "Lush vegetation around the falls"
                        ],
        "significanceTitle":  "Natural Significance",
        "significance":  "Tinago is a prominent freshwater landscape in the Iligan and Lanao del Norte area. Preserving its water quality and surrounding vegetation helps maintain the character of the falls and their pool.",
        "source":  "https://r10.emb.gov.ph/from-progress-to-excellence-tinago-falls-recognized-at-water-summit-2026/",
        "reviews":  null,
        "ratingBreakdown":  null
    }
];
